title:            Sahibinden Labs
description:      kolektif üretim sahası
logo:             site-logo.png
disqus_shortname: sahibindenlabsblog
search:           true
# Change url to your domain. Leave localhost server or blank when working locally.
url:              http://sahibinden.github.io

# Owner/author information
owner:
  name:           Sahibinden Labs
  avatar:         bio-photo.jpg
  email:          labs@sahibinden.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        sahibindenLabs
  facebook:       http://www.facebook.com/pages/Sahibinden-Labs/156713311036060
  github:         sahibinden
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

authors:
  barisguzelordu:
    name:       Barış Güzelordu
    avatar:     barisguzelordu.jpg
    permalink:  baris-guzelordu
    working:    false

  fatihhayrioglu:
    name:       Fatih Hayrioğlu
    avatar:     fatihhayrioglu.jpg
    permalink:  fatih-hayrioglu
    title:      Frontend Developer
    working:    true

  guvendemir:
    name:       Güven Demir
    avatar:     guvendemir.jpg
    permalink:  guven-demir
    title:      Chief Architect
    working:    true

  muratcorlu:
    name:       Murat Çorlu
    avatar:     muratcorlu.jpg
    permalink:  murat-corlu
    working:    true
    title:      Principal Frontend Developer
    twitter:    muratcorlu
    github:     muratcorlu

  sercaneraslan:
    name:       Sercan Eraslan
    avatar:     sercaneraslan.jpg
    permalink:  sercan-eraslan
    title:      Frontend Developer
    working:    true

  serkancapkan:
    name:       Serkan Çapkan
    avatar:     serkancapkan.jpg
    permalink:  serkan-capkan
    working:    false


# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Ekibimiz
    url: /ekibimiz/
  - title: Makaleler
    url: /yazi/
#  - title: Kariyer
#    url: /kariyer/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Istanbul
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /yazi/:title/

relative_permalinks: false

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
